services:
  kalu_app:
    build: .
    container_name: kalu_app
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./instance:/app/instance
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: kalu_tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - kalu_app