version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: mi-web-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  api:
    build: .
    container_name: mi-web-api
    restart: always
    environment:
      - UPLOAD_DIR=/var/www/app/uploads
      - PORT=3001
      - WHATSAPP_PHONE_NUMBER_ID=104868122692292
      - WHATSAPP_API_KEY=EAAY389ZAVFIsBSez7uJZCnyP4O5eelvrOaGfPuZB9iZCYLG0FLf2zvCbtx6IEaADYgKupkGZBlmAM2ucyZBwnvRgtjTptbTGSZBap3mRT06cZBZB6N6NPu7ZBZCKQfUJZCrGkHdL6WtZB3c2UZC7HsS9WaPrdwsIgafx7HA1dIVc5Em9ZBAFtBWeHO3zZCJiEt4Vo9YAqoRmXAZDZD
      - WHATSAPP_VERIFY_TOKEN=kalu_sabanota_secure_token_2026
    volumes:
      - uploads_data:/var/www/app/uploads

volumes:
  uploads_data:
