"""agregar campos a pagos_reportados

Revision ID: 388271f5b475
Revises: e6a265b7113b
Create Date: 2026-04-02 01:09:23.146293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388271f5b475'
down_revision = 'e6a265b7113b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_reportados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplicado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aprobado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo_rechazo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referencia_aplicada', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_pagos_reportados_aprobado_por_id_users', 'users', ['aprobado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_reportados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referencia_aplicada')
        batch_op.drop_column('motivo_rechazo')
        batch_op.drop_column('aprobado_por_id')
        batch_op.drop_column('fecha_aprobacion')
        batch_op.drop_column('aplicado')

    # ### end Alembic commands ###
