"""sincronizar mejoras de seguridad y roles

Revision ID: d4a3a1a747f2
Revises: 388271f5b475
Create Date: 2026-04-16 01:27:57.001802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a3a1a747f2'
down_revision = '388271f5b475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_asientos_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cierres_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarjeta_debito', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_real_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('monto_real_bs', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('diferencia_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('diferencia_bs', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    with op.batch_alter_table('historial_pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_historial_pagos_user_id', 'users', ['user_id'], ['id'])

    # Evitamos borrar campos que podrían ser útiles aunque no estén en el modelo actual
    # with op.batch_alter_table('pagos_reportados', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_pagos_reportados_aprobado_por_id_users', type_='foreignkey')
    #     ...

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_obrero', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.String(length=10), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('nombre_completo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_foreign_key('fk_users_cliente_id', 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key('fk_users_proveedor_id', 'proveedores', ['proveedor_id'], ['id'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_debito_bs', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pago_otros_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('biopago_bdv',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_ventas_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ventas_user_id', type_='foreignkey')
        batch_op.alter_column('biopago_bdv',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('pago_otros_usd')
        batch_op.drop_column('pago_debito_bs')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_proveedor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_cliente_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_completo',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('pin')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('es_obrero')

    with op.batch_alter_table('historial_pagos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_historial_pagos_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cierres_caja', schema=None) as batch_op:
        batch_op.drop_column('observaciones')
        batch_op.drop_column('diferencia_bs')
        batch_op.drop_column('diferencia_usd')
        batch_op.drop_column('monto_real_bs')
        batch_op.drop_column('monto_real_usd')
        batch_op.drop_column('tarjeta_debito')

    with op.batch_alter_table('asientos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asientos_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
